---
- name: Deploy Scientific Calculator
  hosts: all
  become: yes

  tasks:

    - name: Pull Docker Image
      docker_image:
        name: jilspatel/scientific-calculator
        tag: latest
        source: pull

    - name: Remove old container if exists
      docker_container:
        name: calculator_container
        state: absent

    - name: Run Docker Container
      docker_container:
        name: calculator_container
        image: jilspatel/scientific-calculator:latest
        state: started
        restart_policy: always
        ports:
          - "8081:8080"